In [84]:

import torch
import numpy as np
import random

In [85]:
label = [
    [0, 1, 0, 1],
    [0, 1, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 0],
    [0, 1, 1, 1]
]
label = torch.tensor(label)

In [151]:
expected_label = [
    [0, 1, 0, 0],
    [0, 0, 1, 0]
]

In [147]:
#index_expected = expected_label.index(1)
#index_expected = (tf_expected_label == max(tf_expected_label)).nonzero()
#index_expected

In [148]:
#(label == 1)

In [152]:
tf_expected_label = torch.tensor(expected_label)
tf_expected_label.shape

torch.Size([2, 4])

In [155]:
tf_expected_label.transpose(1, 0)

tensor([[0, 0],
        [1, 0],
        [0, 1],
        [0, 0]])

In [156]:
label_index = label.matmul(tf_expected_label.transpose(1, 0))
label_index

tensor([[1, 0],
        [1, 0],
        [1, 1],
        [0, 0],
        [1, 1]])

In [177]:
label_index.transpose(1, 0)

tensor([[1, 1, 1, 0, 1],
        [0, 0, 1, 0, 1]])

In [179]:
label_index_one = (label_index.transpose(1, 0) == 1.0).nonzero()
label_index_one

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 4],
        [1, 2],
        [1, 4]])

In [176]:
label[label_index_one.transpose(0,1)]

tensor([[[0, 1, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 1, 1],
         [0, 1, 1, 1],
         [0, 1, 1, 1],
         [0, 1, 1, 1]],

        [[0, 1, 0, 1],
         [0, 1, 0, 1],
         [0, 1, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 1],
         [0, 1, 0, 0]]])

In [172]:
task_idx = random.sample((list(label_index_one)), 1)
task_idx

[tensor([2, 0])]

In [162]:
label

tensor([[0, 1, 0, 1],
        [0, 1, 0, 0],
        [0, 1, 1, 1],
        [0, 0, 0, 0],
        [0, 1, 1, 1]])

In [163]:
[label[x] for x in task_idx]

[tensor([[0, 1, 0, 0],
         [0, 1, 0, 1]]),
 tensor([[0, 1, 0, 1],
         [0, 1, 0, 1]])]

In [26]:
import torch

a = torch.randn(10)
b = a <= 0
indices = b.nonzero()
print(a, b, indices)

tensor([-0.2380, -1.5193, -0.5560, -2.4470,  0.2277, -1.2537,  1.2606, -0.8237,
        -0.2568,  0.3385]) tensor([ True,  True,  True,  True, False,  True, False,  True,  True, False]) tensor([[0],
        [1],
        [2],
        [3],
        [5],
        [7],
        [8]])
